### ISSUE TITLE
ENH: Add type hints

### ISSUE THREAD

**Issue by corneliusroemer** [ajakubek/python-llist#16]
For some reason VScode doesn't offer any intellisense for llist. Is this a bug in my setup or because there are no type hints and Pylance can't analyse the way this package works because it's pure CPython?

Maybe it would be possible to get method suggestions by adding a type hint file?

This is what I get:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/25161793/214607536-927a1d6d-e4a9-4ceb-85fe-d18d302f8a55.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/25161793/214607667-9b662e3f-12bb-499a-b06a-e6ab7d40aa98.png">

**Comment by ajakubek** [comment]
Hi, support for type hints is now in master.
