### ISSUE TITLE
Support for Python 3.12?

### ISSUE THREAD

**Issue by maresb** [ajakubek/python-llist#18]
Hi! I've been building `llist` for conda-forge. We are [preparing for Python 3.12](https://github.com/conda-forge/llist-feedstock/pull/9) and the test suite is failing. It seems like `test_cyclic_list_destruction_does_not_release_extra_None_refs` ends up in an infinite (or at least unreasonably long) loop:

```
test_cyclic_list_destruction_does_not_release_extra_None_refs (sllist_test.testsllist.test_cyclic_list_destruction_does_not_release_extra_None_refs) ... gc: collecting generation 0...
gc: objects in each generation: 704 0 11671
gc: objects in permanent generation: 375
gc: done, 693 unreachable, 0 uncollectable, 0.0001s elapsed
gc: collecting generation 0...
gc: objects in each generation: 702 9 11671
gc: objects in permanent generation: 375
gc: done, 699 unreachable, 0 uncollectable, 0.0001s elapsed
gc: collecting generation 0...
gc: objects in each generation: 701 12 11671
gc: objects in permanent generation: 375
gc: done, 696 unreachable, 0 uncollectable, 0.0001s elapsed
gc: collecting generation 1...
gc: objects in each generation: 701 17 11671
gc: objects in permanent generation: 375
gc: done, 708 unreachable, 0 uncollectable, 0.0001s elapsed
gc: collecting generation 0...
gc: objects in each generation: 702 0 11680
gc: objects in permanent generation: 375
gc: done, 699 unreachable, 0 uncollectable, 0.0001s elapsed
gc: collecting generation 0...
gc: objects in each generation: 701 3 11680
gc: objects in permanent generation: 375
gc: done, 696 unreachable, 0 uncollectable, 0.0001s elapsed
gc: collecting generation 0...
...
```

Any idea what's going on or how to fix it? Unfortunately I'm not so proficient in C so I can't be of much help myself. Thanks!

**Comment by corneliusroemer** [comment]
Would be great if llist could be made available for Python 3.12

**Comment by ajakubek** [comment]
Hi, the issue is caused by a change in Python 3.12 which results in very high values being returned from [`sys.getrefcount`](https://docs.python.org/3/library/sys.html#sys.getrefcount) for some objects (`None` in this case).

It's not really a problem in C code. I suppose the test cases will simply have to be skipped in Python 3.12 (and later versions).  
I'll prepare a patch this week.

**Comment by maresb** [comment]
Thanks @ajakubek!!!

Would it be possible to get a release of this on PyPI?

**Comment by ajakubek** [comment]
Sure, the plan is to release it this week.  
I just need to make some CI/CD pipeline updates first.

**Comment by creative-resort** [comment]
@ajakubek Anything you'd like help with to make it happen?

**Comment by corneliusroemer** [comment]
What's the status of the Pypi release? Just wondering about conda-forge support for this, ideally we'd also get 3.13 now :)

**Comment by corneliusroemer** [comment]
Looks like Pypi release still hasn't happened yet - I'll make an issue.

<img width="1380" alt="Image" src="https://github.com/user-attachments/assets/3c8c523f-baf4-4c15-8dac-11814799b28d" />

https://pypi.org/project/llist/
